# Generated by Django 3.0 on 2022-05-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of publisher', max_length=50)),
                ('website', models.URLField(help_text="publisher's website")),
                ('email', models.EmailField(help_text="publsiher's email", max_length=254)),
            ],
        ),
    ]
